### ISSUE TITLE
Tasks Tracker

### ISSUE THREAD

**Issue by itaditya** [itaditya/website#66]
- [ ] Move tags to json file and use them in .mdx files.
- [ ] Update Browserlist.
- [ ] Update Nextjs to v11.
- [ ] Fix Cypress pipeline.
- [ ] Replace Buttondown iframe with native form.
- [ ] Fix responsiveness for 13" Macbook.
- [ ] Update Tailwind.
